# Example Configuration File for Correlator Sim
# See https://github.com/Noahfireball1/correlator-sim for updates
general:
  year: 2022
  month: 12
  day: 22
  time: 1200
  verbose: 1
simulation:
  update: scalar # vector or scalar
  sampleFreq: 16.368e6
  initPSR: examplePseudoranges
  initTime: 86465
  time: 50 # [s]
  noise: 0
  CN0: 20
trajectory:
  motion: static
  latitude: 32.5
  longitude: -85.5
  altitude: 0
  velocity: [0 0 0]
  clockBias: 0
  clockDrift: 0
  ionosphereDelay: 0
  troposphereDelay: 0
navigation:
  frequency: 5
plotting:
  docked: 0
  tiled: 0
